Document: django-library
Title: Debian django-library Manual
Author: <insert document author here>
Abstract: This manual describes what django-library is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/django-library/django-library.sgml.gz

Format: postscript
Files: /usr/share/doc/django-library/django-library.ps.gz

Format: text
Files: /usr/share/doc/django-library/django-library.text.gz

Format: HTML
Index: /usr/share/doc/django-library/html/index.html
Files: /usr/share/doc/django-library/html/*.html
